platform :ios, '8.0'

abstract_target 'LunchTimeDefault' do
    pod 'CocoaLumberjack', '~> 2.0.0-rc'
    pod 'AFNetworking', '~>2.6.0'
    pod 'SDWebImage', '~>3.7'
    pod 'JSONModel', '~> 1.0.1'
    pod 'Masonry','~>0.6.1'
    pod 'ReactiveCocoa', '2.5'
    pod 'RealReachability'

    target 'LunchTime' do
        
        target 'LunchTimeTests' do
            inherit! :search_paths
            pod 'Kiwi', '~> 2.3.1'
            pod 'OCMock'
        end
    end
end
